### ISSUE TITLE
웹사이트의 지속가능성

### ISSUE THREAD

**Issue by coder-mina** [womentechkorea/original#2]
## 걱정되는 부분
* [About GitHub Pages](https://help.github.com/en/github/working-with-github-pages/about-github-pages#usage-limits)의 **Usage Limits**를 보면 사용 용량 제한이 1GB인데, 사진 넣고 하다보면 금방 차지 않을까.

* GitHub Pages sites are subject to the following usage limits:
* GitHub Pages source repositories have a recommended limit of 1GB. For more information, see "What is my disk quota?"
Published GitHub Pages sites may be no larger than 1 GB.
* GitHub Pages sites have a soft bandwidth limit of 100GB per month.
* GitHub Pages sites have a soft limit of 10 builds per hour.

**Comment by choch-o** [comment]
Google Photos에 사진을 unlimited로 올릴 수 있으니까 연동하는 건 어떨까요?

간단하게는 https://www.youtube.com/watch?v=InKJcbOgf9k 이런 방법도 있고,
https://developers.google.com/photos/library/guides/access-media-items 여기있는 Google Photo API 이용하는 방법도 있을 것 같아요!

**Comment by coder-mina** [comment]
좋은 정보 고마워요! jekflix 테마로 옮기면서 구글 포토와 연동 완료했어요! 이슈 닫을게요~
