### ISSUE TITLE
글이 안보이는 문제

### ISSUE THREAD

**Issue by pinklady0120** [womentechkorea/original#5]
포스트 수가 많아져서 한 페이지에서 볼 수 있는 갯수가 넘어갔는지, 이전에 쓴 글을 프론트페이지에서 볼 수 없음.

그런데 달리 다음페이지로 넘어갈 수 있는 버튼 같은게 있는게 아니여서 초반글들을 보려면 tag나 이런걸 통해 따로 접근해야함.

**Comment by coder-mina** [comment]
jekflix 테마로 옮기면서 문제 해결되었어요! 이슈 닫을게요~
